apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bookservice
spec:
  replicas: 6
  minReadySeconds: 40
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
        labels:
          app: bookservice
    spec:
      containers:
      - name: bookservice
        image: readymirroring/bookservice-fault
        ports:
        - containerPort: 80
          name: http
        env:
        - name: VERSIONTAG
          value: "V2-RU-BookService"
        - name: INSTRUMENTATION_KEY
          valueFrom:
            secretKeyRef:
              name: appinsightskey
              key: instrumentationkey
---
apiVersion: v1
kind: Service
metadata:
  name: bookservice
spec:
  ports:
  - port: 80
  selector:
    app: bookservice