version: '3.4'

services:
  bookingapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  bookservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

